service: helloworld-app

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  runtime: nodejs8.10
  stage: production
  region: us-east-1
  environment:
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    # reference the NODE_ENV from the secrets.json file

  functions:
    app:
      handler: app.server # reference the file and exported method
      events: # events trigger lambda functions
        - http: # this is an API Gateway HTTP event trigger
          path: /
          method: ANY
          cors: true
        - http: # all routes get proxied to the Express router
          path: /{proxy+}
          method: ANY
          cors: true